# Generated by Django 4.2.29 on 2026-03-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alert', '0001_initial'),
        ('orgs', '__first__'),
        ('devices', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('severity', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('last_event_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.alertrule')),
            ],
        ),
    ]
