# Generated by Django 4.2.29 on 2026-04-02 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_last_seen_at_alter_device_organization_and_more'),
        ('metricSample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricsample',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_samples', to='devices.device'),
        ),
        migrations.AddIndex(
            model_name='metricsample',
            index=models.Index(fields=['device', '-ts'], name='metricSampl_device__1696a9_idx'),
        ),
    ]
