# Generated by Django 4.2.29 on 2026-04-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotesession',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
