# Generated by Django 4.2.29 on 2026-04-02 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='orgs.organization'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
