# Generated by Django 4.2.29 on 2026-03-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='metric',
            field=models.CharField(choices=[('cpu_pct', 'CPU Usage (%)'), ('ram_pct', 'RAM Usage (%)'), ('disk_free_gb', 'Disk Free (GB)'), ('uptime_sec', 'Uptime (Seconds)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='operator',
            field=models.CharField(choices=[('>', 'Greater than'), ('<', 'Less than'), ('>=', 'Greater or equal'), ('<=', 'Less or equal'), ('==', 'Equal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20),
        ),
    ]
